<?php
/** File info
 *
 * @app: Carthook Tests
 * @filename: Products
 * @author: sasokrajnc
 * @datetime: 30/10/2018 - 10:39
 * @version: Products.php, v1.1
 */

namespace My\ProductOrder;

use My\Lib\Functions;
use My\MyAbstractTestCase;

class Products {

    use Functions;

    /*
     * Get product data // DEV
     *
     * @param string $name
     * @return array
     */
    public static function defineProduct($name) {

        // Get current test environment
        $env = MyAbstractTestCase::$currentEnv;

        switch ($name):

            case "Lemons":
                return array("name"                => "Lemons",
                             "variant"             => "",
                             "price"               => "$0.00",
                             "price_clean"         => "0.00",
                             "id"                  => "1727108907106",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047698968674:208e2a70eeb3f586ef33fada6106204b" : "updates_large_17390267760729:6e66917561049a6af18f39ead3810ade",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Orange":
                return array("name"                => "Orange",
                             "variant"             => "",
                             "price"               => "$3.33",
                             "price_clean"         => "3.33",
                             "id"                  => "1727109300322",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047703818338:0f8a875d4fc698430057f62431080a9b" : "updates_large_17390263140441:2b6755925785089c3d6e1d8bb3ed6452",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Peach":
                return array("name"                => "Peach",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$0.00",
                                                                            "price_clean" => "0.00",
                                                                            "id"          => "16047699853410",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047699853410:e310a97c4be77dfa746833e00d2a21b6" : "updates_large_17390263664729:c19b6ace8cf7e2fd4e3687dca2388e46"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$5.00",
                                                                            "price_clean" => "5.00",
                                                                            "id"          => "16047699951714",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047699951714:ea943c5eb96f894963654b964097ba67" : "updates_large_17390263697497:146a84c49d5226831335a9b0b8f1fb27"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$10.00",
                                                                            "price_clean" => "10.00",
                                                                            "id"          => "16047700050018",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047700050018:ceff4e43b7201d157af05a77e5b2bfd4" : "updates_large_17390263730265:44f2bad8a872e4679f94178a5e21307b")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727109038178",
                             "qty_id"              => "",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Apple":
                return array("name"                => "Apple",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$1.00",
                                                                            "price_clean" => "1.00",
                                                                            "id"          => "16047710994530",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047710994530:9fd8aef3093ad2905cfdee2084eb041a" : "updates_large_17390246133849:abcff20bf5a2987f292fa92dee2cca7d"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$100.00",
                                                                            "price_clean" => "100.00",
                                                                            "id"          => "16047711027298",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047711027298:74a9ca890953e3af9b466d73c955d318" : "updates_large_17390246199385:7cefc185ebd952b4f1d91c3756926b20"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$1,000.00",
                                                                            "price_clean" => "1000.00",
                                                                            "id"          => "16047711092834",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047711092834:cc9be751f32925cbcfc243dd608e6a13" : "updates_large_17390246297689:c734a65d7892663bd3e6d1a7e97f3720")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727109595234",
                             "qty_id"              => "",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Kiwi":
                return array("name"                => "Kiwi",
                             "variant"             => "",
                             "price"               => "$0.00",
                             "price_clean"         => "0.00",
                             "id"                  => "1727109431394",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047705817186:f8e3425e5e9081bd7928cf8f2dc78681" : "updates_large_17390255177817:4e0d0f711d39031528eaf7e6bb5e719f",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Banana":
                return array("name"                => "Banana",
                             "variant"             => "",
                             "price"               => "$3.33",
                             "price_clean"         => "3.33",
                             "id"                  => "1727109562466",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047708307554:02c8e698fbd375ee7282646e6a0b499b" : "updates_large_17390249803865:434214668de19cd838263e34439ca125",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Grape":
                return array("name"                => "Grape",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$0.00",
                                                                            "price_clean" => "0.00",
                                                                            "id"          => "16047699034210",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047699034210:01b833c306a22437ce0dafc35d15db40" : "updates_large_17390266744921:ca35bf204900c79f55993d55fd9028f3"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$5.00",
                                                                            "price_clean" => "5.00",
                                                                            "id"          => "16047699066978",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047699066978:f854584451f0d8cd269d2f71560183e0" : "updates_large_17390266810457:edb3b0c8ba831a87b094b32c28174ec2"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$10.00",
                                                                            "price_clean" => "10.00",
                                                                            "id"          => "16047699099746",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047699099746:d910813bbb4d422bd10b75f35627e1b1" : "updates_large_17390266843225:b9b73bd02399a7b8ba8c595b4f0af176")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727108972642",
                             "qty_id"              => "",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;

            case "Avocado":
                return array("name"                => "Avocado",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$1.00",
                                                                            "price_clean" => "1.00",
                                                                            "id"          => "16047705358434",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047705358434:1dafdba0b0d6e3deb5a43692344aa898" : "updates_large_17390260125785:dcbf04ed5736507eb1601358b29fa1c4"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$100.00",
                                                                            "price_clean" => "100.00",
                                                                            "id"          => "16047705423970",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047705423970:3ff87556a1a593e10d984bc5e6309471" : "updates_large_17390260191321:65d582750b4ba9b9520325f0b4dc71db"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$1,000.00",
                                                                            "price_clean" => "1000.00",
                                                                            "id"          => "16047705489506",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047705489506:2ae302c93f20f5d7f35208c044bbc956" : "updates_large_17390260256857:5ae02bff049ea47fadcdabbfbc49845e")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727109333090",
                             "qty_id"              => "",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
                break;
            case "Mouse":
                return array("name"                => "Mouse",
                             "variant"             => "",
                             "price"               => "$0.00",
                             "price_clean"         => "0.00",
                             "id"                  => "1727108841570",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047698935906:1b7973ca890541a4836d22929c8fe2eb" : "updates_large_17390269562969:1c33750087df1a0b34b12c67ddd11d83",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_mouse",
                             "funnel_tag_priority" => 1,
                             "funnel"              => array(0 => array("upsell" => array("funnel_title"              => "Add Mouse to your order today for only $0.00!",
                                                                                         "funnel_product"            => "Mouse",
                                                                                         "funnel_position"           => "1",
                                                                                         "funnel_encoded_partial_id" => ($env == "dev") ? "4olzE7TjTMM44cbMqliZ" : "",
                                                                                         "funnel_price"              => "$0.00",
                                                                                         "funnel_price_clean"        => "0.00",
                                                                                         "funnel_selected_variant"   => "",
                                                                                         "funnel_selected_quantity"  => "1",
                                                                                         "funnel_shipping_clean"     => "0.00"),)));
                break;
            case "Cat":
                return array("name"                => "Cat",
                             "variant"             => "",
                             "price"               => "$3.33",
                             "price_clean"         => "3.33",
                             "id"                  => "2032746266682",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047696871522:e28af108bb173092066540f2ce835d0c" : "updates_large_17390274248793:8a23f9163ce9a28a11e46c43449e0bbe",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_cat",
                             "funnel_tag_priority" => 5,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Cat to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Cat",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "Mj9jkl0LHdCo1UIeJBO3" :"",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Cat to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Cat",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "bRsXGgs66VuG6rgcgpc3" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "",
                                                                                           "funnel_selected_quantity"  => "5",
                                                                                           "funnel_shipping_clean"     => "0.00"))));
                break;

            case "Dog":
                return array("name"                => "Dog",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$0.00",
                                                                            "price_clean" => "0.00",
                                                                            "id"          => "16047696019554",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047696019554:f50b5f7de66deaf0d72159b704569ca7" : "updates_large_17390277328985:c140c31b5a41d44ec87a1ac409cd95f6"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$5.00",
                                                                            "price_clean" => "5.00",
                                                                            "id"          => "16047696052322",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047696052322:fe770aa4603c04d021f769401882f989" : "updates_large_17390277361753:c4458e3b6ff76afd5b6507f5609f28bc"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$10.00",
                                                                            "price_clean" => "10.00",
                                                                            "id"          => "16047696085090",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047696085090:b22799c193687ea3f59f7af952a91cdf" : "updates_large_17390277394521:c1ec787541efeed06c0c407f69daab67")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727108677730",
                             "qty_id"              => "",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_dog",
                             "funnel_tag_priority" => 2,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Dog to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Dog",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "sSQfPv8ASDxdIiVZEnO8" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Dog to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Dog",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "7gUyVWbYtq6amm7PF3fU" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00")),
                                                            1 => array("upsell"   => array("funnel_title"              => "Add Dog to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Dog",
                                                                                           "funnel_position"           => "3",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "WcyezkVNveTfBM3Umrbk" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Dog to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Dog",
                                                                                           "funnel_position"           => "4",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "UQjo5phS8l5Pg4OLx4wi" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"))));
                break;
            case "Tiger":
                return array("name"                => "Tiger",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$1.00",
                                                                            "price_clean" => "1.00",
                                                                            "id"          => "16047695331426",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047695331426:c5926957ec611ccad4df6c35463b6bf9" : "updates_large_17390280081497:84f13d2ee8e3ced9c442dd5c0df0f5f2"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$100.00",
                                                                            "price_clean" => "100.00",
                                                                            "id"          => "16047695364194",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047695364194:1acc72ac0110ef6225b6404facb5a848" : "updates_large_17390280147033:6215489d6649cb8bba5926b88d82b546"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$1,000.00",
                                                                            "price_clean" => "1000.00",
                                                                            "id"          => "16047695396962",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047695396962:e40b238e6355218298b5db554c6766ae" : "updates_large_17390280212569:335fe78505f29dbfba3c9dc61dfac0bc")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727108612194",
                             "qty_id"              => "",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_tiger",
                             "funnel_tag_priority" => 6,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "TLDkMc0HQWjupQvf0dGo" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "fwboPZEf1i1kI8qChDdX" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00")),
                                                            1 => array("upsell"   => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "3",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "z3Jhb54jWewpVfSdHsEp" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "4",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "RDKzJXS6nZo4UwKXeD06" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00")),
                                                            2 => array("upsell"   => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "5",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "uvSlOIMLsBATnkmo6gfP" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Tiger to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Tiger",
                                                                                           "funnel_position"           => "6",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "9deIa4C2s9oP51fTMWgY" : "",
                                                                                           "funnel_price"              => "$1.00",
                                                                                           "funnel_price_clean"        => "1.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "0.00"))
                                 ));
                break;

            case "Bicycle":
                return array("name"                => "Bicycle",
                             "variant"             => "",
                             "price"               => "$0.00",
                             "price_clean"         => "0.00",
                             "id"                  => "1727108513890",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047694676066:c77708706a573cf083da7caa316e4ade" : "updates_large_17390286274649:072f97503b82df7426519aa73859dd90",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_bicycle",
                             "funnel_tag_priority" => 4,
                             "funnel"              => array(0 => array("upsell" => array("funnel_title"              => "Add Bicycle to your order today for only $0.00!",
                                                                                         "funnel_product"            => "Bicycle",
                                                                                         "funnel_position"           => "1",
                                                                                         "funnel_encoded_partial_id" => ($env == "dev") ? "P3bsVh2ccVFsaUEd49LP" : "",
                                                                                         "funnel_price"              => "$0.00",
                                                                                         "funnel_price_clean"        => "0.00",
                                                                                         "funnel_selected_variant"   => "",
                                                                                         "funnel_selected_quantity"  => "1",
                                                                                         "funnel_shipping_clean"     => "5.00"),)));
                break;

            case "Motorcycle":
                return array("name"                => "Motorcycle",
                             "variant"             => "",
                             "price"               => "$3.33",
                             "price_clean"         => "3.33",
                             "id"                  => "2032746266682",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047694643298:1d43583840ac75d8a4537c06c16a85d0" : "updates_large_17390286864473:89f16e263c98aaea8dbc8f05b004498a",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_motor",
                             "funnel_tag_priority" => 7,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Motorcycle to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Motorcycle",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "BJC22KjejibJlZ3HRBNQ" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "5.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Motorcycle to your order today for only $0.00!",
                                                                                           "funnel_product"            => "Motorcycle",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "dkubY29Q74zRFGDSl9mf" : "",
                                                                                           "funnel_price"              => "$0.00",
                                                                                           "funnel_price_clean"        => "0.00",
                                                                                           "funnel_selected_variant"   => "",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00"))));
                break;

            case "Car":
                return array("name"                => "Car",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$0.00",
                                                                            "price_clean" => "0.00",
                                                                            "id"          => "16047692644450",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047692644450:9841074ba85c70c154c6e0ac34502f5b" : "updates_large_17390290436185:29019e3da7fcaaca39fc459265d25911"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$5.00",
                                                                            "price_clean" => "5.00",
                                                                            "id"          => "16047692709986",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047692709986:fba49a8616cd8eacb45d3814c2fd6331" : "updates_large_17390290534489:34c301a31c8a2306ff988a9e773e45a5"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$10.00",
                                                                            "price_clean" => "10.00",
                                                                            "id"          => "16047692775522",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047692775522:4bb2dd68435f9bdb17694a0f892a432a" : "updates_large_17390290698329:090e3f32f9628526f7b7e81b1aa74dd0")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727108382818",
                             "qty_id"              => "",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_car",
                             "funnel_tag_priority" => 3,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Car to your order today for only $5.00!",
                                                                                           "funnel_product"            => "Car",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "7CYesXvDdRKG41kP3Ohd" : "",
                                                                                           "funnel_price"              => "$5.00",
                                                                                           "funnel_price_clean"        => "5.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Car to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Car",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "tT5hIDMzb2SDF7MYkIRV" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00")),
                                                            1 => array("upsell"   => array("funnel_title"              => "Add Car to your order today for only $5.00!",
                                                                                           "funnel_product"            => "Car",
                                                                                           "funnel_position"           => "3",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "mYr4SW1hCBSruEgrPfHM" : "",
                                                                                           "funnel_price"              => "$5.00",
                                                                                           "funnel_price_clean"        => "5.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "5.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Car to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Car",
                                                                                           "funnel_position"           => "4",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "Vp8ABztWDZuRWFVykxG3" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00"))));
                break;

            case "Plane":
                return array("name"                => "Plane",
                             "variant"             => array("var1" => array("name"        => "S",
                                                                            "price"       => "$1.00",
                                                                            "price_clean" => "1.00",
                                                                            "id"          => "16047689826402",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047689826402:1945ef9c43a74c87f84209fee94bbb62" : "updates_large_17390298923097:d00d6291352ca1089eeb8cd015462f13"),
                                                            "var2" => array("name"        => "M",
                                                                            "price"       => "$100.00",
                                                                            "price_clean" => "100.00",
                                                                            "id"          => "16047689924706",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047689924706:23703cd84126482455bb449ce5988127" : "updates_large_17390298955865:2f7075909c9e8978b7733ce1cf2a1408"),
                                                            "var3" => array("name"        => "L",
                                                                            "price"       => "$1,000.00",
                                                                            "price_clean" => "1000.00",
                                                                            "id"          => "16047689990242",
                                                                            "qty_id"      => ($env == "dev") ? "updates_large_16047689990242:7449ea97c32ceeb5846d5955c39b77f2" : "updates_large_17390299086937:4abf588defed7526bc1d09b3e7bf8259")),
                             "price"               => "",
                             "price_clean"         => "",
                             "id"                  => "1727108317282",
                             "qty_id"              => "",
                             "tax"                 => true,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "carthook_plane",
                             "funnel_tag_priority" => 8,
                             "funnel"              => array(0 => array("upsell"   => array("funnel_title"              => "Add Plane to your order today for only $5.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "1",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "U6Axtu2eWVBeHlMus3Jt" : "",
                                                                                           "funnel_price"              => "$5.00",
                                                                                           "funnel_price_clean"        => "5.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Plane to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "2",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "AC1q9aCve9cmt3MF6ZAW" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00")),
                                                            1 => array("upsell"   => array("funnel_title"              => "Add Plane to your order today for only $5.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "3",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "3APIy6IIpUphdNpPITFi" : "",
                                                                                           "funnel_price"              => "$5.00",
                                                                                           "funnel_price_clean"        => "5.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "5",
                                                                                           "funnel_shipping_clean"     => "5.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Plane to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "4",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "MQLhyQaAw1f2VrhWqx9M" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00")),
                                                            2 => array("upsell"   => array("funnel_title"              => "Add Plane to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "5",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "jO836orCtp4imUWmE7aY" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "2",
                                                                                           "funnel_shipping_clean"     => "10.00"),
                                                                       "downsell" => array("funnel_title"              => "Add Plane to your order today for only $10.00!",
                                                                                           "funnel_product"            => "Plane",
                                                                                           "funnel_position"           => "6",
                                                                                           "funnel_encoded_partial_id" => ($env == "dev") ? "eqcXMnn5X6YQFN0RJ3Lx" : "",
                                                                                           "funnel_price"              => "$10.00",
                                                                                           "funnel_price_clean"        => "10.00",
                                                                                           "funnel_selected_variant"   => "S",
                                                                                           "funnel_selected_quantity"  => "1",
                                                                                           "funnel_shipping_clean"     => "10.00"))));
                break;

            default:
                return array("name"                => "Lemons",
                             "variant"             => "",
                             "price"               => "$0.00",
                             "price_clean"         => "0.00",
                             "id"                  => "1727108907106",
                             "qty_id"              => ($env == "dev") ? "updates_large_16047698968674:208e2a70eeb3f586ef33fada6106204b" : "updates_large_17390267760729:6e66917561049a6af18f39ead3810ade",
                             "tax"                 => false,
                             "body_html"           => "<p>Test.</p>",
                             "currency"            => "USD",
                             "sku"                 => "",
                             "vendor"              => "",
                             "handle"              => "",
                             "details"             => "",
                             "funnel_tag"          => "",
                             "funnel_tag_priority" => 0,
                             "funnel"              => false);
        endswitch;
    }

    /*
     * Get funnel partial id
     *
     * @param string $product
     * @param int $funnelPosition
     * @return int
     */
    public static function getFunnelPartialId($product, $funnelPosition) {

        // Get product details
        $productData = self::defineProduct($product);

        // Set encoded id to false
        $funnelEncodedId = 0;

        // Loop though the funnel steps
        foreach ($productData['funnel'] as $funnelStep) {

            // Loop through the funnel type
            foreach ($funnelStep as $partialType => $partialDetails) {

                // If position is found, get enccoded partial id
                if ($partialDetails['funnel_position'] == $funnelPosition) {

                    $funnelEncodedId = $partialDetails['funnel_encoded_partial_id'];
                }
            }
        }

        return ($funnelEncodedId) ? $funnelEncodedId : false;
    }
}